//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;

namespace WAQS.Entities
{
    public class DbValuesDictionary
    {
    	private Dictionary<string, object> _dico = new Dictionary<string, object>();
    
    	public bool Add(string key, Func<object> getValue)
    	{
    		if (_dico.ContainsKey(key))
    			return false;
    		_dico.Add(key, getValue());
    		return true;
    	}
    
    	public object this[string key]
    	{
    		get { return _dico[key]; }
    	}
    }
}
