//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System.Collections;
using System.Collections.Generic;

namespace WAQS.ClientContext
{
    public class QueryPage<T> : IEnumerable<T>
    {
        private IEnumerable<T> _enumerable;
    
        public QueryPage(int pageIndex, IEnumerable<T> enumerable)
        {
            PageIndex = pageIndex;
            _enumerable = enumerable;
        }
    
        public int PageIndex { get; private set; }
    
        public IEnumerator<T> GetEnumerator()
        {
            return _enumerable.GetEnumerator();
        }
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
}
