//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 

namespace WAQS.DAL
{
    public abstract class ObjectContextCustomizer<T>  : ObjectContextCustomizerBase<T>
        where T : ObjectContextCustomizer<T>, new()
    {
        public static OC CreateObjectContext<OC>(OC objectContext)
            where OC : CustomizableObjectContext
        {
            objectContext.AddSaveAction(new T { ObjectContext = objectContext }.SaveChanges);
            objectContext.AddSaveAsyncAction(new T { ObjectContext = objectContext }.SaveChangesAsync);
            return objectContext;
        }
    }
}
