//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System.Runtime.Serialization;

namespace WAQS.SerializableExpressions
{
    [DataContract(Namespace = "http://WAQS/QuerySerialization", IsReference = true)]
    [KnownType(typeof(SerializableBinaryExpression))]
    [KnownType(typeof(SerializableUnaryExpression))]
    [KnownType(typeof(SerializableEntitySetExpression))]
    [KnownType(typeof(SerializableMemberExpression))]
    [KnownType(typeof(SerializableMethodCallExpression))]
    [KnownType(typeof(SerializablePropertyGetterExpression))]
    [KnownType(typeof(SerializablePropertySetterExpression))]
    [KnownType(typeof(SerializableConstructorExpression))]
    [KnownType(typeof(SerializableLambdaExpression))]
    [KnownType(typeof(SerializableParameterExpression))]
    [KnownType(typeof(SerializableConstantExpression))]
    [KnownType(typeof(SerializableMemberInitExpression))]
    [KnownType(typeof(SerializableConditionalExpression))]
    [KnownType(typeof(SerializableTypeBinaryExpression))]
    public abstract class SerializableExpression
    {
        protected internal abstract void Visit(SerializableExpressionVisitor visitor);
    }
}
