//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using System.ServiceModel;
using WAQS.SerializableExpressions;
using WAQS.Service.Interfaces;
using WAQS.WCFService.Contract;
using WAQSWorkshopServer;
using WAQSWorkshopServer.Service.Interfaces;
using WAQSWorkshopServer.WAQSDTO;

namespace WAQSWorkshopServer.WCFService.Contract
{
    [ServiceContract(Namespace="http://Northwind.net", Name="INorthwindService")]
    [NorthwindFaults]
    public partial interface INorthwindWCFService
    {	
    	[OperationContract]
    	NorthwindQueryResult Execute(QuerySerialization query);
    
    	[OperationContract]
    	NorthwindQueriesResult ExecuteMany(QueriesSerialization queries);
    
    	[OperationContract]
    	NorthwindQueryResultPage LoadPage(int pageSize, SerializableExpression queryExpression, string[] withSpecificationsProperties, LoadPageParameter[] identifiers);
    
    	[OperationContract]
    	DateTime GetDbDateTime();
    	
    	[OperationContract]
    	NorthwindSerializableContext SaveChanges(NorthwindSerializableContext context);
    
    	[OperationContract(Name="ValidateCustomer")]
    	List<Error> Validate(Customer entity);
    
    	[OperationContract(Name="ValidateEmployee")]
    	List<Error> Validate(Employee entity);
    
    	[OperationContract(Name="ValidateInvoiceDetail")]
    	List<Error> Validate(InvoiceDetail entity);
    
    	[OperationContract(Name="ValidateInvoice")]
    	List<Error> Validate(Invoice entity);
    
    	[OperationContract(Name="ValidateOrderDetail")]
    	List<Error> Validate(OrderDetail entity);
    
    	[OperationContract(Name="ValidateOrder")]
    	List<Error> Validate(Order entity);
    
    	[OperationContract(Name="ValidateProduct")]
    	List<Error> Validate(Product entity);
    
    	[OperationContract(Name="ValidateCategory")]
    	List<Error> Validate(Category entity);
    
    	[OperationContract]
    	bool AlreadySoldTo(Employee employee, Customer customer);
    
    	[OperationContract]
    	Invoice AddInvoice(int orderId);
    
    	[OperationContract]
    	InvoiceDetail CreateInvoiceDetail(OrderDetail od);
    
    	[OperationContract]
    	LastOrderDTO GetLastOrder();
    }
}
