//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System.Windows;
using System.Windows.Controls;
using WAQS.ClientContext;
using WAQS.ClientContext.Interfaces;

namespace WAQS.Controls
{
    public partial class NavigationPanel : UserControl
    {
    	public NavigationPanel()
    	{
    		InitializeComponent();
    		LayoutRoot.DataContext = this;
    	}
    	
    	public IPaginatedQuery Source
    	{
    		get { return (IPaginatedQuery)GetValue(SourceProperty); }
    		set { SetValue(SourceProperty, value); }
    	}
    	public static readonly DependencyProperty SourceProperty = DependencyProperty.Register("Source", typeof(IPaginatedQuery), typeof(NavigationPanel), new PropertyMetadata((s, e) => ((NavigationPanel)s).Source = (IPaginatedQuery)e.NewValue));
    }
}
