//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using System.Linq;
using WAQS.ClientContext;
using WAQS.ClientContext.Interfaces;
using WAQS.EntitiesTracking;
using WAQSWorkshopClient.ClientContext.Interfaces;

namespace WAQSWorkshopClient.ClientContext
{
    public static partial class NorthwindClientEntitySetExtensions
    {
    }
}
