//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Markup;
using System.Windows.Media;
using System.Xml;
using WAQS.ClientContext.Interfaces.Errors;

namespace WAQS.Controls
{
    public partial class ErrorsBehaviors
    {
        public static ObservableCollection<Error> GetErrors(DependencyObject obj)
        {
            return (ObservableCollection<Error>)obj.GetValue(ErrorsProperty);
        }
    
        public static void SetErrors(DependencyObject obj, ObservableCollection<Error> value)
        {
            obj.SetValue(ErrorsProperty, value);
        }
    
        // Using a DependencyProperty as the backing store for Errors.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty ErrorsProperty =
            DependencyProperty.RegisterAttached("Errors", typeof(ObservableCollection<Error>), typeof(ErrorsBehaviors), new PropertyMetadata((d, e) =>
            {
                bool done = false;
                AttachErrors(d, e, ref done);
                if (done)
                {
                    return;
                }
    
                FrameworkElement frameworkElement = null;
                var control = d as Control;
                Func<Thickness> getBorderThickness = null;
                Func<Brush> getBorderBrush = null;
                Action<Thickness> setBorderThickness = null;
                Action<Brush> setBorderBrush = null;
                if (control == null)
                {
                    var border = d as Border;
                    if (border != null)
                    {
                        frameworkElement = border;
                        getBorderThickness = () => border.BorderThickness;
                        getBorderBrush = () => border.BorderBrush;
                        setBorderThickness = t => border.BorderThickness = t;
                        setBorderBrush = brush => border.BorderBrush = brush;
                    }
                }
                else
                {
                    frameworkElement = control;
                    getBorderThickness = () => control.BorderThickness;
                    getBorderBrush = () => control.BorderBrush;
                    setBorderThickness = t => control.BorderThickness = t;
                    setBorderBrush = brush => control.BorderBrush = brush;
                }
                var errors = e.NewValue as ObservableCollection<Error>;
                if (frameworkElement == null || errors == null)
                    return;
    
                var errorsListBox = (ListBox)XamlReader.Load(new XmlTextReader(new StringReader(string.Concat("<ListBox xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' ><ListBox.ItemTemplate><DataTemplate xmlns:errorsConveters='clr-namespace:WAQS.Controls.Converters;assembly=", Assembly.GetExecutingAssembly().GetName().Name, "'><DataTemplate.Resources><errorsConveters:CritityConverter x:Key='CriticityConverter' /></DataTemplate.Resources><Grid><Grid.ColumnDefinitions><ColumnDefinition Width='15' /><ColumnDefinition Width='5' /><ColumnDefinition /></Grid.ColumnDefinitions><Image Source='{Binding Criticity, Converter={StaticResource CriticityConverter}}'/><TextBlock Grid.Column='2' Text='{Binding Message}' /></Grid></DataTemplate></ListBox.ItemTemplate></ListBox>"))));
                var errorsCollectionViewSource = new CollectionViewSource { Source = errors };
                errorsCollectionViewSource.SortDescriptions.Add(new SortDescription("Criticity", ListSortDirection.Descending));
                errorsListBox.SetBinding(ListBox.ItemsSourceProperty, new Binding { Source = errorsCollectionViewSource });
                var toolTip = new ToolTip { Content = errorsListBox };
                ToolTipService.SetToolTip(frameworkElement, toolTip);
                ToolTipService.SetIsEnabled(frameworkElement, false);
    
                var oldBorderThickness = getBorderThickness();
                var oldBorderBrush = getBorderBrush();
                NotifyCollectionChangedEventHandler errorsCollectionChanged = (_, __) =>
                    {
                        var maxCriticity = errors.Select(er => er.Criticity).OrderByDescending(c => c).FirstOrDefault();
                        done = false;
                        SetControlStyle(frameworkElement, errors, maxCriticity, ref done);
                        if (!done)
                        {
                            switch (maxCriticity)
                            {
                                case Criticity.Error:
                                case Criticity.Mandatory:
                                    setBorderThickness(new Thickness(2));
                                    setBorderBrush(Brushes.Red);
                                    ToolTipService.SetIsEnabled(frameworkElement, true);
                                    break;
                                case Criticity.Warning:
                                    setBorderThickness(new Thickness(2));
                                    setBorderBrush(Brushes.Orange);
                                    ToolTipService.SetIsEnabled(frameworkElement, true);
                                    break;
                                case Criticity.Information:
                                    setBorderThickness(oldBorderThickness);
                                    setBorderBrush(oldBorderBrush);
                                    ToolTipService.SetIsEnabled(frameworkElement, true);
                                    break;
                                case Criticity.None:
                                    setBorderThickness(oldBorderThickness);
                                    setBorderBrush(oldBorderBrush);
                                    ToolTipService.SetIsEnabled(frameworkElement, false);
                                    break;
                            }
                        }
                    };
                errors.CollectionChanged += errorsCollectionChanged;
                errorsCollectionChanged(null, null);
                RoutedEventHandler controlUnloaded = null;
                controlUnloaded = (_, __) =>
                    {
                        frameworkElement.Unloaded -= controlUnloaded;
                        errors.CollectionChanged -= errorsCollectionChanged;
                    };
                frameworkElement.Unloaded += controlUnloaded;
            }));
    
        static partial void AttachErrors(DependencyObject d, DependencyPropertyChangedEventArgs e, ref bool done);
    
        static partial void SetControlStyle(FrameworkElement control, ObservableCollection<Error> errors, Criticity maxCriticity, ref bool done);
    }
}
