//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 

namespace WAQS.ComponentModel
{
    public partial class ValidateErrorInfo : ErrorInfo
    {
    	public const string ValidateErrorCode = "Validate";
    	private string _message;
    
    	public ValidateErrorInfo(string message)
    		: base(ValidateErrorCode)
    	{
    		_message = message;
    	}
    
    	public override string Message 
    	{ 
    		get { return _message; } 
    	}
    }
}
