//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace WAQS.DAL.Interfaces
{
    public interface IWAQSQueryBase
    {
        IDataContext DataContext { get; }
        IEnumerable<Func<IWAQSQueryBase, QueryableInclude>> QueryableIncludes { get; set; }
        IEnumerable<string> WithSpecifications { get; set; }
        Func<Expression, Expression> ExpressionTransformation { get; }
        bool FromQuery { get; set; }
    }
}
