//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System.Windows;

namespace WAQS.Controls
{
    public class MessageBoxService : WAQS.ComponentModel.IMessageBoxService
    {
    	public void ShowError(string message)
    	{
    		MessageBox.Show(message);
    	}
    }
}
