//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace WAQS.ClientContext.QueryResult
{
    [DataContract(Namespace = "http://WAQS/QueryResult")]
    public class QueryResultProperty
    {
        [DataMember]
        public string PropertyName { get; set; }
    
        [DataMember]
        public string SerializedValue { get; set; }
    
        [DataMember]
        public QueryResultRecord Value { get; set; }
    
        [DataMember]
        public List<QueryResultRecord> Values { get; set; } 
    }
}
