//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System.Threading.Tasks;
using System.Windows.Threading;

namespace WAQS.ComponentModel
{
    public static partial class UIThread
    {
    	public static Dispatcher Dispatcher { get; set; }
    	public static TaskScheduler TaskScheduler { get; set; }
    }
}
