//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using WAQS.Service.Interfaces;

namespace WAQS.Service
{
    public class ValidationException : Exception
    {
        public ValidationException(IEnumerable<Error> errors)
        {
            _errors = errors;
        }
        
        private IEnumerable<Error> _errors;
        public IEnumerable<Error> Errors 
        { 
            get { return _errors; } 
        }
    }
}
