//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

            using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using WAQS.Entities;
using WAQS.Service.Interfaces;
using WAQS.Specifications;

namespace WAQSWorkshopServer
{
    partial class Employee
    {
        [DataContract(Namespace = "http://Northwind/Entities")]
        public partial class EmployeeSpecifications
        {
            [DataMember]
            public string FullName
            {
                get;
                set;
            }

            [DataMember]
            public bool HasFullName
            {
                get;
                set;
            }
        }

        [DataMember]
        public EmployeeSpecifications Specifications
        {
            get;
            set;
        }

        protected EmployeeSpecifications GetSpecifications()
        {
            return Specifications ?? (Specifications = GetSpecificationsEmployee());
        }

        protected virtual EmployeeSpecifications GetSpecificationsEmployee()
        {
            return new EmployeeSpecifications();
        }

        [Specifications]
        public string GetFullName()
        {
            return this.FirstName + " " + this.LastName;
        }

        [Specifications]
        public string FullName
        {
            get
            {
                return GetSpecifications().HasFullName ? GetSpecifications().FullName : GetFullName();
            }

            set
            {
                GetSpecifications().FullName = value;
                GetSpecifications().HasFullName = true;
            }
        }

        [Specifications]
        public bool AlreadySoldTo(Customer customer)
        {
            if (customer == null || customer.Orders == null)
                return default (bool);
            return customer.Orders.Any(o =>
            {
                if (o == null)
                    return default (bool);
                return o.EmployeeId == this.Id;
            }

            );
        }
    }
}
            