//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;

namespace WAQS.Common
{
    public static class EnumUtils
    {
        public static T GetEnumValue<T>(string enumName)
        {
            var enumNames = Enum.GetNames(typeof(T));
            for (int i = 0, length = enumNames.Length; i < length; i++)
                if (enumNames[i] == enumName)
                    return (T)Enum.GetValues(typeof(T)).GetValue(i);
            throw new ArgumentException();
        }
    }
}
