//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;

namespace WAQS.Common
{
    public partial class ExceptionDetail<T> : IExceptionDetail
        where T : Exception
    {
        public ExceptionDetail(T exception)
        {
            Initialize(exception);
        }
    
        partial void Initialize(T exception);
    
        public string Message { get; protected set; }
        public IEnumerable<object> Entities { get; protected set; }
    }
}
