//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using System.Linq;
using WAQS.WCFService.Contract;

namespace WAQSWorkshopServer.WCFService.Contract
{
    public partial class NorthwindFaultsAttribute : StandardFaultsAttribute
    {
    	protected override List<Type> GetFaultTypes()
    	{
    		var value = base.GetFaultTypes();
    		value.Add(typeof(NorthwindFaultDetailEntities));
    		GetFaultTypes(ref value);
    		return value;
    	}
    
    	partial void GetFaultTypes(ref List<Type> types);
    }
}
