//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace WAQS.ClientContext
{
    public class Grouping<TKey, TElement> : IGrouping<TKey, TElement>
    {
        public Grouping(TKey key, List<TElement> elements)
        {
            Key = key;
            _elements = elements;
        }
    
        private List<TElement> _elements;
        private List<TElement> Elements
        {
            get { return _elements ?? (_elements = new List<TElement>()); }
        }
    
        public TKey Key { get; set; }
    
        public IEnumerator<TElement> GetEnumerator()
        {
            return Elements.GetEnumerator();
        }
    
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
}
