//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;

namespace WAQS.ClientContext.Interfaces
{
    public static class ClientContextFactory<T> 
    	where T : IClientContext
    {
        public static Func<T> Factory { get; set; }
    
        public static T Create()
        {
            return Factory();
        }
    }
}
