//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 

namespace WAQS.ComponentModel
{
    public abstract partial class ErrorInfo
    {
        public ErrorInfo(string errorCode)
        {
        	ErrorCode = errorCode;
        }
        		
        public ErrorInfo(string propertyName, string errorCode)
        {
            PropertyName = propertyName;
        	ErrorCode = errorCode;
        }
        		
        public string PropertyName { get; private set; }
    	public string ErrorCode { get; private set; }
    	public abstract string Message { get; }
    	
    	public override string ToString()
    	{
    		return Message;
    	}
    }
}
